### ISSUE TITLE
sxos : crash switch at start of the game

### ISSUE THREAD

**Issue by DevilScarlet** [three-houses-research-team/Aldebaran#1]
I should have properly delete exfs_patchs, exfs and starfall folder
I put the new files from aldebaran, renamed atmosphere to sxos, content to titles
I didn't edit the config.txt since I don't plan/know how to use the remote connect
Game works fine and is in 1.2.0 without aldebaran but when I put aldebaran without any module, game crash and the switch crash too.
Did I do something wrong? is there any issue with sxos? (starfall and everything till now for atmos is working fine on it too)

**Comment by Raytwo** [comment]
Wow, that sounds like a very complex issue.
Everything works fine on regular AMS but my SX OS is not up to date yet.
Could you try running it on AMS and see if you encounter the same issue?
I might speak without knowing here but I'd suspect this is caused by one of the numerous changes/code removal performed by the SX OS team on Atmosphere and unfortunately I can't really work around that.

**Comment by DevilScarlet** [comment]
I don't have any atmos switch :c I don't know what could cause this; starfall on 1.1.1 did work fine but I don't know what differ between starfall and aldebaran

**Comment by Raytwo** [comment]
So far, nothing except the added TCP logging.
However I do not really plan to update Starfall past 1.1.1.
But well, considering this is -technically- the last update to the game, maybe I can make an exception.

**Comment by DevilScarlet** [comment]
if you could it would be great, on my side i'm trying to triple boot sxos atmos android.... poor switch

**Comment by Raytwo** [comment]
Haha, good luck with that.
No promises but I'll try doing it by tonight.

**Comment by DevilScarlet** [comment]
sxos & atmos is easy enough, there's a guide, for android thought har
and don't push yourself but to be honest I would be happy if you could haha

**Comment by DevilScarlet** [comment]
So I confirm, no issue on atmos with the exact same game and aldebaran.
It's just that aldebaran is incompatible with sxos, well guess I will play FE3H on atmos now lol

**Comment by Raytwo** [comment]
Oh well, perfect then.
Thanks for letting me know though, hopefully you're the only one running into that issue.
Have fun!
